### PR TITLE
Create multiselect menu with items preselected

### PR DESCRIPTION
**Pull request by UnstoppableDrew**
Added parameter preselected_entries, a list of menu_entries items to be pre-checked in a multiselect menu.

I didn't add a corresponding entry to the argument parse, I wasn't sure if that was {des|requ}ired but I can go back and add it if necessary.

### CODE REVIEW

**Comment by IngoMeyer441** [comment]
Thanks for your code contribution, tested and works! :smiley: 
I think there are some small issues with this PR yet:
- [ ] It would be great if `preselected_entries` could also be an `Iterable[int]` (so in combination an `Iterable[Union[int, str]]`) to be compatible with the `cursor_index` parameter which is also an `int`.
- [ ] It is probably cleaner to pass `preselected_entries` to the `Selection` constructor instead of the `View` constructor.
- [ ] Mypy complains about a missing `index` method on `Iterable[str]`, see [line 280](https://github.com/UnstoppableDrew/simple-term-menu/blob/preselected/simple_term_menu.py#L280). I think this could be fixed with something like
     ```python
     entry_to_index = {entry: i for i, entry in enumerate(menu_entries)}
     for preselected_entry in preselected_entries:
         idx = entry_to_index[preselected_entry]
         self._selection.add(idx)
     ```
- [ ] I am not quite sure what should be done if `multi_select` is False but `preselected_entries` are present. Perhaps an error should be raised or `multi_select` must be forced to be `True`.
- [ ] Please add a short description of the new parameter to the README file.
- [ ] A command line parameter would be really great since all other parameters can also be used from the command line.

Sorry, the list got longer than I initially thought. :sweat_smile: I can try to help though (I think I will have some time this week).

**Comment by UnstoppableDrew** [comment]
Thanks for the feedback. While looking at the issues you raised I've already had several ideas of how to do it better, and I will add the README and CLI parameter too.

**Comment by UnstoppableDrew** [comment]
Reworked, now handles strings & ints, put in error checks, cli args & the README.

**Comment by UnstoppableDrew** [comment]
Is mypy running with arguments? I ran it locally (just 'mypy simple_menu_term.py') and it didn't complain.

**Comment by IngoMeyer441** [comment]
Thanks for all the changes. I am currently quite busy but I can review them tomorrow morning. :+1: 

> Is mypy running with arguments? I ran it locally (just 'mypy simple_menu_term.py') and it didn't complain.

Yes, usually you can simply pass the filename to `mypy`. Personally, I run `mypy` with the `--strict` option to avoid any untyped code in my modules.

**Comment by IngoMeyer441** [comment]
I reviewed the code and it works great! :+1: I only applied some improvements:

- The help text of the CLI is updated in the README.
- The `TerminalMenu` constructor checks if `multi_select` is enabled if `preselected_entries` are given. If not, an `InvalidParameterCombinationError` is raised.
- `preselected_entries` is allowed to contain both integers and strings, so API users have maximum flexibility.
- The type of `preselected_entries` is changed from `Sequence` to `Iterable` to be more generic and match the other constructor parameter types.
- The code block which checks the `preselected_entries` is put into a sub function (only my personal preference, I like code to be structured into logical blocks with sub functions).
- Strings in `preselected_entries` are mapped to the menu items with a dict instead of the `index` method. I suppose it is more efficient to iterate only once over all menu items (for the dict creation) because the later key lookup is O(1) on a Python dict. This way it is also possible to find more than one index if some menu entries have the same name (but ok, that is an edge case).
- If a menu entry cannot be found, an `UnknownMenuEntryError` is raised.
- Both new exceptions are caught when the CLI is run, so not the stack trace but only the error message is printed to console.

The patch file for these changes is attached (it is a zipped with gzip because otherwise GitHub does not allow the upload :disappointed:). You can apply them to your latest `preselected` branch (commit `f3c85be`) with `git apply`:

```bash
gunzip preselected.patch.gz
git apply preselected.patch
```

What do you think about these changes? I am always open for other opinions.

[preselected.patch.gz](https://github.com/IngoMeyer441/simple-term-menu/files/6907901/preselected.patch.gz)

**Comment by UnstoppableDrew** [comment]
Those look good to me, I've applied your patch.

**Comment by IngoMeyer441** [comment]
Thanks for your contribution @UnstoppableDrew! I have squashed your commits and merged the squashed commit into develop (commit 50c34db57ae5abe84cac52e1c63cde1ea8c88155, I am the committer but you are still the commit author, so your contribution is shown on GitHub). Because of the squashing GitHub does not auto-detect that your changes are now merged, so I close your PR manually.
Your changes are part of the latest [v1.3.0 release](https://github.com/IngoMeyer441/simple-term-menu/releases/tag/v1.3.0).

**Pull request closed without merging**
