### PR TITLE
New Option to raise KeyboardInterrupt

### PR DESCRIPTION
**Pull request by svartkanin**
Introducing a new option to make the menu raise an KeyboardInterrupt instead of quitting silently

### CODE REVIEW

**Comment by svartkanin** [comment]
@IngoMeyer441 any chance to get this merged or is there any changes needed?

**Comment by IngoMeyer441** [comment]
Sorry @svartkanin, I wanted to send to some change suggestions (directly as code) but was always busy with other tasks. I think your PR is useful and should be added to simple-term-menu. I have only a few things that could be changed:

- Instead of `explode` I would use the term `raise`. 
- Options in the constructor are sorted by default currently.
- I am not sure if we really need a cli option for this. Is there a use case for raising an exception to the terminal instead of returning an error code with an error message?

**Comment by svartkanin** [comment]
@IngoMeyer441 yes I can rename it to `raise` instead and also add it in a sorted way :) 
Regarding the cli option, I just wanted to keep it consistent with the rest of constructor options being available. But I agree, it might not be as useful, so I can remove it

**Comment by svartkanin** [comment]
@IngoMeyer441 I've addressed all feedback and updated the PR :)

**Comment by IngoMeyer441** [comment]
Thanks again! It is merged into `develop`. I added a small notice in the README explaining your new parameter. And sorry (again) for the long waiting time...

**Pull request closed without merging**
