### PR TITLE
changed behaviour of enter key during multiselection

### PR DESCRIPTION
**Pull request by raulparada**
Hi there 👋 

First of all, thanks a lot for this package! tested several and this was the only one that checked all the boxes.

Only minor change that I'd like to suggest is the behaviour of the 'enter' key while doing multiple selection. In my humble opinion it's bad UX that hitting 'enter' to finish the selection also adds the current highlighted item; why? 'cause if I as user read a hint a là "spacebar to select, enter to confirm" I cannot get from this that I cannot have highlighted something I don't intend to be selected. Impact can be major if I don't get this right (using this for a production CLI).

Especially when using the preview function (amazing btw) I may want to scroll further than the items I've selected to check if there's still something that should be included, and don't want to come back on a huge list just to make sure I'm over a selected item.

With this small change only spacebar adds to the selection—unless there's nothing selected, in which case it conforms to single selection and enter selects and confirms.

Please consider it :) cheers

### CODE REVIEW

**Comment by IngoMeyer441** [comment]
Hey @raulparada,
glad to hear that this project is useful for you! :slightly_smiling_face: 
I didn't think about the possibility to scroll through all menu items and look for other previews without wanting to select the currently highlighted item when pressing the accept key. But this is a good point and I think we should add your change somehow. But I am not sure how to integrate it because it changes the multi-selection logic and other users are affected as well. Perhaps we could add another bool parameter to the `TerminalMenu` constructor to change the accept logic?

**Comment by raulparada** [comment]
Thanks for having a look so fast @IngoMeyer441 :)

Reasonable yes, may implement during the day... would `multi_select_select_on_accept` be ok? a bit redundant but cannot think of something else

**Comment by IngoMeyer441** [comment]
`multi_select_select_on_accept` is good. :+1: I can also help with implementing this (but not today, sorry). Things that should be considered:
- [ ] `TerminalMenu` constructor parameter
- [ ] (optional) option for the command line program
- [ ] README update

**Comment by raulparada** [comment]
(I butchered those commits but) I think I got there. When you find the time let me know, cheers!

**Comment by IngoMeyer441** [comment]
Thanks for your changes :slightly_smiling_face:.
I have added some changes to support your new flag in the command line interface and the bool operator was missing for the `Selection` class:
```diff
diff --git a/README.md b/README.md
index 8b64da3..e54acfd 100644
--- a/README.md
+++ b/README.md
@@ -215,7 +215,9 @@ currently selected entry as the last item to the selection and to return from th
 multi-select mode, the `show` method returns a sorted tuple of all your selected menu indices instead of a single int.
 Use the `chosen_menu_entries` property to get a tuple of the menu entry strings instead. By setting `multi_select_key`
 you can define another key to toggle a selected item. By passing `show_multi_select_hint=True` a multi-select mode hint
-is shown in the status bar. If you don't want the `accept_key` to also select the last highlighted item you can pass `multi_select_select_on_accept=False`
+is shown in the status bar. If you don't want the `accept_key` to also select the last highlighted item you can pass
+`multi_select_select_on_accept=False` (if no menu item is explicitly selected, the last highlighted menu item will still
+be added to the selection).
 
 #### Multi-select example
 
@@ -387,6 +389,7 @@ usage: simple-term-menu [-h] [-s] [-X] [-l] [--cursor CURSOR]
                         [--multi-select-cursor MULTI_SELECT_CURSOR]
                         [--multi-select-cursor-style MULTI_SELECT_CURSOR_STYLE]
                         [--multi-select-key MULTI_SELECT_KEY]
+                        [--multi-select-no-select-on-accept]
                         [-p PREVIEW_COMMAND] [--preview-size PREVIEW_SIZE]
                         [-V] [--search-highlight-style SEARCH_HIGHLIGHT_STYLE]
                         [--search-key SEARCH_KEY]
@@ -431,6 +434,10 @@ optional arguments:
   --multi-select-key MULTI_SELECT_KEY
                         key for toggling a selected item in a multi-selection
                         (default: " ",
+  --multi-select-no-select-on-accept
+                        do not select the currently highlighted menu item when
+                        the accept key is pressed (it is still selected if no
+                        other item was selected before)
   -p PREVIEW_COMMAND, --preview PREVIEW_COMMAND
                         Command to generate a preview for the selected menu
                         entry. "{}" can be used as placeholder for the menu
diff --git a/simple_term_menu.py b/simple_term_menu.py
index c62cf45..172bec0 100755
--- a/simple_term_menu.py
+++ b/simple_term_menu.py
@@ -232,6 +232,9 @@ class TerminalMenu:
             self[menu_index] = menu_index not in self._selected_menu_indices
             return self[menu_index]
 
+        def __bool__(self) -> bool:
+            return bool(self._selected_menu_indices)
+
         def __contains__(self, menu_index: int) -> bool:
             return menu_index in self._selected_menu_indices
 
@@ -1296,11 +1299,8 @@ class TerminalMenu:
                         self._selection.toggle(self._view.active_menu_index)
                 elif next_key in current_menu_action_to_keys["accept"]:
                     if self._view.active_menu_index is not None:
-                        if self._multi_select_select_on_accept:
+                        if self._multi_select_select_on_accept or not self._selection:
                             self._selection.add(self._view.active_menu_index)
-                        else:
-                            if not self._selection:
-                                self._selection.add(self._view.active_menu_index)
                     self._chosen_accept_key = next_key
                     break
                 elif next_key in current_menu_action_to_keys["quit"]:
@@ -1463,6 +1463,15 @@ def get_argumentparser() -> argparse.ArgumentParser:
         default=DEFAULT_MULTI_SELECT_KEY,
         help=('key for toggling a selected item in a multi-selection (default: "%(default)s", '),
     )
+    parser.add_argument(
+        "--multi-select-no-select-on-accept",
+        action="store_false",
+        dest="multi_select_select_on_accept",
+        help=(
+            "do not select the currently highlighted menu item when the accept key is pressed "
+            "(it is still selected if no other item was selected before)"
+        ),
+    )
     parser.add_argument(
         "-p",
         "--preview",
@@ -1658,6 +1667,7 @@ def main() -> None:
             multi_select_key=args.multi_select_key,
             multi_select_cursor=args.multi_select_cursor,
             multi_select_cursor_style=args.multi_select_cursor_style,
+            multi_select_select_on_accept=args.multi_select_select_on_accept,
             show_multi_select_hint=args.show_multi_select_hint,
         )
     except InvalidStyleError as e:
```
You can save these changes to a file (`multiselect-on-enter.patch` for example) and run
```bash
git apply multiselect-on-enter.patch
```
to adopt the changes. But of course I am also open for other changes!
After committing the changes, you can squash all the commits to a single commit with an interactive rebase:
```bash
git rebase -i origin/develop
```
Git will open an editor with a commit overview for you. You can change all `pick`s to `squash` (or simple `s`) except the first one to meld all commits into the first commit.

**Comment by raulparada** [comment]
hahaha, I'll disappear to learn git properly for a while and come back eventually....
Thanks a lot for the help @IngoMeyer441! sorry to bother

**Comment by YAMLcase** [comment]
@IngoMeyer441 can you make a branch with these changes and I'll test it out? I'm suffering the same UX friction as @raulparada and would love to help improve this.  Thanks

**Comment by YAMLcase** [comment]
ahh, yes it helps to read more thoroughly :) multi_select_select_on_accept=False as an option does indeed work as expected.  thanks @raulparada !

**Pull request closed without merging**
