### PR TITLE
Fixes wrong display on loops (linux)

### PR DESCRIPTION
**Pull request by faanbece**
- Title parameter is omitted (now title is manually). Title generates visualization errors within the loops.
- Generalize the screen wipe function.

### CODE REVIEW

**Comment by IngoHeimbach** [comment]
Thanks for supporting my project! :smiley: I think you found a bug since menu titles should be displayed correctly without manual printing. The last version of `simple-term-menu` broke the support for trailing `\n` characters in the title. I will look into this and commit a patch.

**Comment by IngoHeimbach** [comment]
I have added some new commits which are included in the latest release `v0.5.0`:
- dd6dd260f9f9abf76b6190da1662e6bde4205768 adds support for multiline titles (including empty lines for vertical space)
- c970dfef4e1dcc0a287b2989f3a31daf0863e807 adds an option to clear the screen with a terminal escape code, so the user doesn't need to call `clear` or `cls`.

**Comment by faanbece** [comment]
Hi, that was fast.

**Comment by faanbece** [comment]
That was fast.

**Comment by IngoHeimbach** [comment]
I am currently working on a new feature for a preview window anyway, so I could create a quick fix...

**Comment by IngoHeimbach** [comment]
I would like to merge your commit 3e82f37700f15fc329082c3a4643507d6a9d3cf4. Could you rebase it onto the current develop?

**Review by Seluj78 — APPROVED** [review]

**Comment by IngoMeyer441** [comment]
> I would like to merge your commit [3e82f37](https://github.com/IngoMeyer441/simple-term-menu/commit/3e82f37700f15fc329082c3a4643507d6a9d3cf4). Could you rebase it onto the current develop?

Done in #59, thanks @ScoreUnder.

**Pull request closed without merging**
